resolver 127.0.0.11 valid=10s ipv6=off;

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $upstream_gateway http://order-gateway:8080;
        proxy_pass $upstream_gateway;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        set $upstream_auth http://identity-provider:4001;
        proxy_pass $upstream_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
