global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "identity-provider"
    scheme: https
    static_configs:
      - targets: ["iut-cafeteria-crisis-deployed.onrender.com"]
    metrics_path: "/metrics"

  - job_name: "stock-service"
    scheme: https
    static_configs:
      - targets: ["stock-service-xril.onrender.com"]
    metrics_path: "/metrics"

  - job_name: "order-gateway"
    scheme: https
    static_configs:
      - targets: ["order-gateway.onrender.com"]
    metrics_path: "/metrics"

  - job_name: "kitchen-service"
    scheme: https
    static_configs:
      - targets: ["kitchen-service-ux9y.onrender.com"]
    metrics_path: "/metrics"

  - job_name: "notification-hub"
    scheme: https
    static_configs:
      - targets: ["notification-hub-eeob.onrender.com"]
    metrics_path: "/metrics"
